version = "1.0"

[main]
name.en = "Shared directories"
name.fr = "Répertoires partagés"
services = ["smbd"]

[main.main]
	name = ""
	optional = true

[main.main.directories]
	ask.en = "List of shared directories"
	ask.fr = "Liste des répertoires partagés"
	type = "tags"
	optional = false
	help.en = "Use space bar to define multiple directories at once. Use enter/return key to apply changes."
	help.fr = "Pour définir plusieurs répertoires à la fois, utiliser la barre d'espace. Pour appliquer les changements, utiliser la touche entrée/retour à la ligne."

[main.main.advanced]
	ask.en = "Advanced parameters"
	ask.fr = "Paramètres avancés"
	type = "boolean"
	
[main.main.readonly_dir]
	ask.en = "List of readonly directories"
	ask.fr = "Liste des répertoires en lecture seule"
	type = "tags"
	visible = "advanced"
	icon = "folder"
	help.en = "Directories must be first defined and the configuration saved before appearing here."
	help.fr = "Pour apparaitre ici, le répertoire doit être d'abord défini et la configuration sauvegardée."

[main.main.unbrowseable]
	ask.en = "List of invisible directories"
	ask.fr = "Liste des répertoires cachés"
	type = "tags"
	visible = "advanced"
	icon = "folder"
	help.en = "Directories must be first defined and the configuration saved before appearing here."
	help.fr = "Pour apparaitre ici, le répertoire doit être d'abord défini et la configuration sauvegardée."
