#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

if yunohost service status smbd >/dev/null
then
	ynh_script_progression "Removing smbd service integration..."
	yunohost service remove smbd
fi

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
